### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Horizon221** [Loyalists/GFLMW2#1]
This happen after i started the second mission in act 1, suddenly it's frozen and the sound still on, i can't get out from the program or go to my desktop cause it's frozen, so i have to restart the laptop, then i go to the folder and find this

![Screenshot (33)](https://user-images.githubusercontent.com/82234014/114223372-f1c1fb80-9999-11eb-901f-557d7b510b9c.png)

this file that has this name appear after the error, i don't know what is this but maybe you can help

Edit : okay so i can't screenshot the error but i write it' it's say 

Fatal error (0x000005) at 0x00526aaO, a mini dump has been written to SP - 10.04.2021 00-56-38

Edit: got the screenshot 
![Screenshot (36)](https://user-images.githubusercontent.com/82234014/114226800-45cedf00-999e-11eb-8f94-52cce73938b6.png)

**Comment by Loyalists** [comment]
The error doesn't appear in the steam version. According to some users non-steam copies seem to be incompatible with the mod.

**Comment by ovsyanka063** [comment]
even though I have a steam version, but I also have the same error when starting the first and second missions.

**Comment by dendemonlord** [comment]
![image](https://user-images.githubusercontent.com/130400395/230979887-6d03a683-8a60-48b3-884e-f6e8c33b4ed2.png)
![image](https://user-images.githubusercontent.com/130400395/230980026-ed9ce595-6a11-4e76-b797-6f151e0bf4cf.png)
how to fix this?
